2025-08-28 20:16:51,037 - INFO - Application starting...
2025-08-28 20:16:51,397 - DEBUG - Starting new HTTPS connection (1): api.telegra.ph:443
2025-08-28 20:16:52,207 - DEBUG - https://api.telegra.ph:443 "POST /createAccount/ HTTP/1.1" 200 216
2025-08-28 20:16:53,155 - DEBUG - Not in REPL -> leaving logger event level as is.
2025-08-28 20:16:53,161 - DEBUG - Looking for locale `en_US` in provider `faker.providers.address`.
2025-08-28 20:16:53,166 - DEBUG - Provider `faker.providers.address` has been localized to `en_US`.
2025-08-28 20:16:53,169 - DEBUG - Looking for locale `en_US` in provider `faker.providers.automotive`.
2025-08-28 20:16:53,173 - DEBUG - Provider `faker.providers.automotive` has been localized to `en_US`.
2025-08-28 20:16:53,174 - DEBUG - Looking for locale `en_US` in provider `faker.providers.bank`.
2025-08-28 20:16:53,177 - DEBUG - Specified locale `en_US` is not available for provider `faker.providers.bank`. Locale reset to `en_GB` for this provider.
2025-08-28 20:16:53,178 - DEBUG - Looking for locale `en_US` in provider `faker.providers.barcode`.
2025-08-28 20:16:53,179 - DEBUG - Provider `faker.providers.barcode` has been localized to `en_US`.
2025-08-28 20:16:53,181 - DEBUG - Looking for locale `en_US` in provider `faker.providers.color`.
2025-08-28 20:16:53,184 - DEBUG - Provider `faker.providers.color` has been localized to `en_US`.
2025-08-28 20:16:53,185 - DEBUG - Looking for locale `en_US` in provider `faker.providers.company`.
2025-08-28 20:16:53,188 - DEBUG - Provider `faker.providers.company` has been localized to `en_US`.
2025-08-28 20:16:53,189 - DEBUG - Looking for locale `en_US` in provider `faker.providers.credit_card`.
2025-08-28 20:16:53,191 - DEBUG - Provider `faker.providers.credit_card` has been localized to `en_US`.
2025-08-28 20:16:53,192 - DEBUG - Looking for locale `en_US` in provider `faker.providers.currency`.
2025-08-28 20:16:53,196 - DEBUG - Provider `faker.providers.currency` has been localized to `en_US`.
2025-08-28 20:16:53,197 - DEBUG - Looking for locale `en_US` in provider `faker.providers.date_time`.
2025-08-28 20:16:53,201 - DEBUG - Provider `faker.providers.date_time` has been localized to `en_US`.
2025-08-28 20:16:53,203 - DEBUG - Provider `faker.providers.doi` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2025-08-28 20:16:53,203 - DEBUG - Provider `faker.providers.emoji` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2025-08-28 20:16:53,203 - DEBUG - Provider `faker.providers.file` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2025-08-28 20:16:53,204 - DEBUG - Looking for locale `en_US` in provider `faker.providers.geo`.
2025-08-28 20:16:53,205 - DEBUG - Provider `faker.providers.geo` has been localized to `en_US`.
2025-08-28 20:16:53,206 - DEBUG - Looking for locale `en_US` in provider `faker.providers.internet`.
2025-08-28 20:16:53,209 - DEBUG - Provider `faker.providers.internet` has been localized to `en_US`.
2025-08-28 20:16:53,210 - DEBUG - Looking for locale `en_US` in provider `faker.providers.isbn`.
2025-08-28 20:16:53,211 - DEBUG - Provider `faker.providers.isbn` has been localized to `en_US`.
2025-08-28 20:16:53,212 - DEBUG - Looking for locale `en_US` in provider `faker.providers.job`.
2025-08-28 20:16:53,214 - DEBUG - Provider `faker.providers.job` has been localized to `en_US`.
2025-08-28 20:16:53,215 - DEBUG - Looking for locale `en_US` in provider `faker.providers.lorem`.
2025-08-28 20:16:53,218 - DEBUG - Provider `faker.providers.lorem` has been localized to `en_US`.
2025-08-28 20:16:53,218 - DEBUG - Looking for locale `en_US` in provider `faker.providers.misc`.
2025-08-28 20:16:53,219 - DEBUG - Provider `faker.providers.misc` has been localized to `en_US`.
2025-08-28 20:16:53,220 - DEBUG - Looking for locale `en_US` in provider `faker.providers.passport`.
2025-08-28 20:16:53,221 - DEBUG - Provider `faker.providers.passport` has been localized to `en_US`.
2025-08-28 20:16:53,221 - DEBUG - Looking for locale `en_US` in provider `faker.providers.person`.
2025-08-28 20:16:53,226 - DEBUG - Provider `faker.providers.person` has been localized to `en_US`.
2025-08-28 20:16:53,229 - DEBUG - Looking for locale `en_US` in provider `faker.providers.phone_number`.
2025-08-28 20:16:53,234 - DEBUG - Provider `faker.providers.phone_number` has been localized to `en_US`.
2025-08-28 20:16:53,235 - DEBUG - Provider `faker.providers.profile` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2025-08-28 20:16:53,235 - DEBUG - Provider `faker.providers.python` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2025-08-28 20:16:53,236 - DEBUG - Provider `faker.providers.sbn` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2025-08-28 20:16:53,236 - DEBUG - Looking for locale `en_US` in provider `faker.providers.ssn`.
2025-08-28 20:16:53,240 - DEBUG - Provider `faker.providers.ssn` has been localized to `en_US`.
2025-08-28 20:16:53,241 - DEBUG - Provider `faker.providers.user_agent` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2025-08-28 20:16:53,993 - INFO - MainWindow.__init__ started.
2025-08-28 20:16:54,042 - INFO - MainWindow.__init__ finished.
2025-08-28 20:16:59,460 - DEBUG - Starting new HTTPS connection (1): api.proxyscrape.com:443
2025-08-28 20:16:59,994 - ERROR - Error in worker thread for get_proxy_list: maximum recursion depth exceeded
Traceback (most recent call last):
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\gui.py", line 377, in run_tool
    with contextlib.redirect_stdout(output_stream): self.func()
                                                    ~~~~~~~~~^^
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\script\tools\proxy_fetcher.py", line 19, in get_proxy_list
    response = requests.get(proxy_api_url, timeout=15, verify=False)
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
        method=request.method,
    ...<9 lines>...
        chunked=chunked,
    )
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\urllib3\connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
    ~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\urllib3\connectionpool.py", line 1093, in _validate_conn
    conn.connect()
    ~~~~~~~~~~~~^^
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\urllib3\connection.py", line 790, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
        sock=sock,
    ...<14 lines>...
        assert_fingerprint=self.assert_fingerprint,
    )
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\urllib3\connection.py", line 922, in _ssl_wrap_socket_and_match_hostname
    context = create_urllib3_context(
        ssl_version=resolve_ssl_version(ssl_version),
    ...<2 lines>...
        cert_reqs=resolve_cert_reqs(cert_reqs),
    )
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\urllib3\util\ssl_.py", line 303, in create_urllib3_context
    context.minimum_version = TLSVersion.TLSv1_2
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ShShu\AppData\Local\Programs\Python\Python313\Lib\ssl.py", line 545, in minimum_version
    super(SSLContext, SSLContext).minimum_version.__set__(self, value)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ShShu\AppData\Local\Programs\Python\Python313\Lib\ssl.py", line 545, in minimum_version
    super(SSLContext, SSLContext).minimum_version.__set__(self, value)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ShShu\AppData\Local\Programs\Python\Python313\Lib\ssl.py", line 545, in minimum_version
    super(SSLContext, SSLContext).minimum_version.__set__(self, value)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  [Previous line repeated 983 more times]
RecursionError: maximum recursion depth exceeded
