2025-08-28 20:45:18,472 - INFO - Application starting...
2025-08-28 20:45:18,834 - DEBUG - Starting new HTTPS connection (1): api.telegra.ph:443
2025-08-28 20:45:19,478 - DEBUG - https://api.telegra.ph:443 "POST /createAccount/ HTTP/1.1" 200 214
2025-08-28 20:45:20,455 - DEBUG - Not in REPL -> leaving logger event level as is.
2025-08-28 20:45:20,460 - DEBUG - Looking for locale `en_US` in provider `faker.providers.address`.
2025-08-28 20:45:20,466 - DEBUG - Provider `faker.providers.address` has been localized to `en_US`.
2025-08-28 20:45:20,468 - DEBUG - Looking for locale `en_US` in provider `faker.providers.automotive`.
2025-08-28 20:45:20,474 - DEBUG - Provider `faker.providers.automotive` has been localized to `en_US`.
2025-08-28 20:45:20,475 - DEBUG - Looking for locale `en_US` in provider `faker.providers.bank`.
2025-08-28 20:45:20,477 - DEBUG - Specified locale `en_US` is not available for provider `faker.providers.bank`. Locale reset to `en_GB` for this provider.
2025-08-28 20:45:20,478 - DEBUG - Looking for locale `en_US` in provider `faker.providers.barcode`.
2025-08-28 20:45:20,479 - DEBUG - Provider `faker.providers.barcode` has been localized to `en_US`.
2025-08-28 20:45:20,481 - DEBUG - Looking for locale `en_US` in provider `faker.providers.color`.
2025-08-28 20:45:20,483 - DEBUG - Provider `faker.providers.color` has been localized to `en_US`.
2025-08-28 20:45:20,484 - DEBUG - Looking for locale `en_US` in provider `faker.providers.company`.
2025-08-28 20:45:20,488 - DEBUG - Provider `faker.providers.company` has been localized to `en_US`.
2025-08-28 20:45:20,489 - DEBUG - Looking for locale `en_US` in provider `faker.providers.credit_card`.
2025-08-28 20:45:20,490 - DEBUG - Provider `faker.providers.credit_card` has been localized to `en_US`.
2025-08-28 20:45:20,491 - DEBUG - Looking for locale `en_US` in provider `faker.providers.currency`.
2025-08-28 20:45:20,494 - DEBUG - Provider `faker.providers.currency` has been localized to `en_US`.
2025-08-28 20:45:20,495 - DEBUG - Looking for locale `en_US` in provider `faker.providers.date_time`.
2025-08-28 20:45:20,498 - DEBUG - Provider `faker.providers.date_time` has been localized to `en_US`.
2025-08-28 20:45:20,499 - DEBUG - Provider `faker.providers.doi` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2025-08-28 20:45:20,499 - DEBUG - Provider `faker.providers.emoji` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2025-08-28 20:45:20,499 - DEBUG - Provider `faker.providers.file` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2025-08-28 20:45:20,500 - DEBUG - Looking for locale `en_US` in provider `faker.providers.geo`.
2025-08-28 20:45:20,501 - DEBUG - Provider `faker.providers.geo` has been localized to `en_US`.
2025-08-28 20:45:20,502 - DEBUG - Looking for locale `en_US` in provider `faker.providers.internet`.
2025-08-28 20:45:20,506 - DEBUG - Provider `faker.providers.internet` has been localized to `en_US`.
2025-08-28 20:45:20,507 - DEBUG - Looking for locale `en_US` in provider `faker.providers.isbn`.
2025-08-28 20:45:20,508 - DEBUG - Provider `faker.providers.isbn` has been localized to `en_US`.
2025-08-28 20:45:20,509 - DEBUG - Looking for locale `en_US` in provider `faker.providers.job`.
2025-08-28 20:45:20,512 - DEBUG - Provider `faker.providers.job` has been localized to `en_US`.
2025-08-28 20:45:20,513 - DEBUG - Looking for locale `en_US` in provider `faker.providers.lorem`.
2025-08-28 20:45:20,515 - DEBUG - Provider `faker.providers.lorem` has been localized to `en_US`.
2025-08-28 20:45:20,516 - DEBUG - Looking for locale `en_US` in provider `faker.providers.misc`.
2025-08-28 20:45:20,516 - DEBUG - Provider `faker.providers.misc` has been localized to `en_US`.
2025-08-28 20:45:20,517 - DEBUG - Looking for locale `en_US` in provider `faker.providers.passport`.
2025-08-28 20:45:20,518 - DEBUG - Provider `faker.providers.passport` has been localized to `en_US`.
2025-08-28 20:45:20,519 - DEBUG - Looking for locale `en_US` in provider `faker.providers.person`.
2025-08-28 20:45:20,524 - DEBUG - Provider `faker.providers.person` has been localized to `en_US`.
2025-08-28 20:45:20,527 - DEBUG - Looking for locale `en_US` in provider `faker.providers.phone_number`.
2025-08-28 20:45:20,531 - DEBUG - Provider `faker.providers.phone_number` has been localized to `en_US`.
2025-08-28 20:45:20,532 - DEBUG - Provider `faker.providers.profile` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2025-08-28 20:45:20,532 - DEBUG - Provider `faker.providers.python` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2025-08-28 20:45:20,532 - DEBUG - Provider `faker.providers.sbn` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2025-08-28 20:45:20,532 - DEBUG - Looking for locale `en_US` in provider `faker.providers.ssn`.
2025-08-28 20:45:20,537 - DEBUG - Provider `faker.providers.ssn` has been localized to `en_US`.
2025-08-28 20:45:20,538 - DEBUG - Provider `faker.providers.user_agent` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2025-08-28 20:45:21,275 - INFO - MainWindow.__init__ started.
2025-08-28 20:45:21,322 - INFO - MainWindow.__init__ finished.
2025-08-28 20:45:24,696 - DEBUG - Starting new HTTPS connection (1): api.proxyscrape.com:443
2025-08-28 20:45:35,004 - DEBUG - Starting new HTTPS connection (1): www.1secmail.com:443
2025-08-28 20:45:35,133 - ERROR - Error in worker thread for temp_mail: maximum recursion depth exceeded
Traceback (most recent call last):
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\gui.py", line 377, in run_tool
    with contextlib.redirect_stdout(output_stream): self.func()
                                                    ~~~~~~~~~^^
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\script\tools\temp_mail.py", line 45, in temp_mail
    available_domains = get_domains()
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\script\tools\temp_mail.py", line 11, in get_domains
    response = requests.get("https://www.1secmail.com/api/v1/?action=getDomainList")
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
        method=request.method,
    ...<9 lines>...
        chunked=chunked,
    )
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\urllib3\connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
    ~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\urllib3\connectionpool.py", line 1093, in _validate_conn
    conn.connect()
    ~~~~~~~~~~~~^^
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\urllib3\connection.py", line 790, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
        sock=sock,
    ...<14 lines>...
        assert_fingerprint=self.assert_fingerprint,
    )
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\urllib3\connection.py", line 931, in _ssl_wrap_socket_and_match_hostname
    context.verify_mode = resolve_cert_reqs(cert_reqs)
    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ShShu\AppData\Local\Programs\Python\Python313\Lib\ssl.py", line 679, in verify_mode
    super(SSLContext, SSLContext).verify_mode.__set__(self, value)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ShShu\AppData\Local\Programs\Python\Python313\Lib\ssl.py", line 679, in verify_mode
    super(SSLContext, SSLContext).verify_mode.__set__(self, value)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ShShu\AppData\Local\Programs\Python\Python313\Lib\ssl.py", line 679, in verify_mode
    super(SSLContext, SSLContext).verify_mode.__set__(self, value)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  [Previous line repeated 983 more times]
RecursionError: maximum recursion depth exceeded
2025-08-28 20:45:37,381 - DEBUG - Starting new HTTPS connection (1): www.1secmail.com:443
2025-08-28 20:45:37,494 - ERROR - Error in worker thread for temp_mail: maximum recursion depth exceeded
Traceback (most recent call last):
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\gui.py", line 377, in run_tool
    with contextlib.redirect_stdout(output_stream): self.func()
                                                    ~~~~~~~~~^^
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\script\tools\temp_mail.py", line 45, in temp_mail
    available_domains = get_domains()
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\script\tools\temp_mail.py", line 11, in get_domains
    response = requests.get("https://www.1secmail.com/api/v1/?action=getDomainList")
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
        method=request.method,
    ...<9 lines>...
        chunked=chunked,
    )
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\urllib3\connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
    ~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\urllib3\connectionpool.py", line 1093, in _validate_conn
    conn.connect()
    ~~~~~~~~~~~~^^
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\urllib3\connection.py", line 790, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
        sock=sock,
    ...<14 lines>...
        assert_fingerprint=self.assert_fingerprint,
    )
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\urllib3\connection.py", line 931, in _ssl_wrap_socket_and_match_hostname
    context.verify_mode = resolve_cert_reqs(cert_reqs)
    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ShShu\AppData\Local\Programs\Python\Python313\Lib\ssl.py", line 679, in verify_mode
    super(SSLContext, SSLContext).verify_mode.__set__(self, value)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ShShu\AppData\Local\Programs\Python\Python313\Lib\ssl.py", line 679, in verify_mode
    super(SSLContext, SSLContext).verify_mode.__set__(self, value)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ShShu\AppData\Local\Programs\Python\Python313\Lib\ssl.py", line 679, in verify_mode
    super(SSLContext, SSLContext).verify_mode.__set__(self, value)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  [Previous line repeated 983 more times]
RecursionError: maximum recursion depth exceeded
